from .TCPConnection import TCPConnection
from .UDPConnection import UDPConnection
from .NetworkSharedBytes import addNetworkSharedBytes, setNetworkSharedBytes, NetworkSharedBytes, networkSharedBytesInit