# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngame.proto\"\"\n\nCoordinate\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"\xab\x01\n\x06Player\x12\x11\n\tplayer_id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x1d\n\x08position\x18\x03 \x01(\x0b\x32\x0b.Coordinate\x12\x19\n\x04\x62ody\x18\x04 \x03(\x0b\x32\x0b.Coordinate\x12\r\n\x05score\x18\x05 \x01(\x05\x12\x0c\n\x04\x64irX\x18\x06 \x01(\x02\x12\x0c\n\x04\x64irY\x18\x07 \x01(\x02\x12\x17\n\x0fhead_image_path\x18\x08 \x01(\t\"1\n\x04\x46ood\x12\x1d\n\x08position\x18\x01 \x01(\x0b\x32\x0b.Coordinate\x12\n\n\x02id\x18\x02 \x01(\t\"\x82\x01\n\x08GameData\x12\x18\n\x07players\x18\x01 \x03(\x0b\x32\x07.Player\x12\x14\n\x05\x66oods\x18\x02 \x03(\x0b\x32\x05.Food\x12\r\n\x05\x61live\x18\x03 \x01(\x08\x12\r\n\x05score\x18\x04 \x01(\x05\x12\x12\n\nfood_eaten\x18\x05 \x01(\x05\x12\x14\n\x0c\x62oundary_box\x18\x06 \x03(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'game_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_COORDINATE']._serialized_start=14
  _globals['_COORDINATE']._serialized_end=48
  _globals['_PLAYER']._serialized_start=51
  _globals['_PLAYER']._serialized_end=222
  _globals['_FOOD']._serialized_start=224
  _globals['_FOOD']._serialized_end=273
  _globals['_GAMEDATA']._serialized_start=276
  _globals['_GAMEDATA']._serialized_end=406
# @@protoc_insertion_point(module_scope)